### ISSUE TITLE
> getting transformed to &gt;

### ISSUE THREAD

**Issue by jaydeepbasu** [Automattic/syntaxhighlighter#159]
Using SyntaxHighlighter Evolved plugin when adding `<plugin>abcd</plugin>` in blog it is rendering as `<plugin&gt;abcd</plugin&gt;`
Using latest version of wordpress and the plugin.

**Comment by alexsanford** [comment]
Looks like this is a duplicate of https://github.com/Automattic/syntaxhighlighter/issues/108

I haven't been able to reproduce this, so there is something we're missing here. A few questions:

- Are you using the block editor, or the classic editor with shortcodes?
- If using the block editor, what are the Block settings? What "Code Language" is selected?
- If using shortcodes, which shortcode and options are you using?
- Have you tried with all other plugins on the site disabled?

**Comment by jaydeepbasu** [comment]
I am using Block Editor, as I was putting xml in the block so the language is set to HTML/XML and no other settings apart from that.
I am only using JetPack plugin.
I haven't tried by disabling the JetPack plugin as that plugin is mandatory for me.
Any suggestions?

**Comment by alexsanford** [comment]
Hmmm. I just spun up a fresh site with only Jetpack, using the Twenty Twenty theme, and this is what I see on the frontend:

<img width="1288" alt="Screen Shot 2020-07-24 at 10 27 28" src="https://user-images.githubusercontent.com/842193/88395995-6ecc2700-cdb1-11ea-9dea-09d8b3bb74b2.png">

What theme are you using? Could you test with Twenty Twenty and see whether that changes anything?

Here's what my block settings look like. Anything look different for you?

<img width="1294" alt="Screen Shot 2020-07-24 at 10 30 03" src="https://user-images.githubusercontent.com/842193/88396255-cb2f4680-cdb1-11ea-823d-48adc9686b18.png">

**Comment by jaydeepbasu** [comment]
Though I might sound illogical but I am no longer facing the issue, I have done no version upgrade,not a single change but it is working now. Yesterday I installed the plugin for the first time and when i faced the issue I tried all possible ways to correct it but it didn;t work, 12 hours after that it started working.
Request you to please keep it open, in case i face it again, i can update here in comment.

**Comment by alexsanford** [comment]
It's better to close this issue at this point, since it is not a reproducible bug. But comments will still be open, and the issue can be reopened if the bug comes up again, so please feel free to give any new information if that happens 🙂

**Comment by l2m83** [comment]
Hello,
We had a similar problem, it seems that it occured for users that are not administrator (ex: Editor).

**Comment by coreymckrill** [comment]
I've discovered a way to consistently reproduce this issue:

* Set up a _multisite_ installation of WordPress, install the SyntaxHighlighter plugin.
* Create two users on the site, a super admin and an editor.
* With each user, publish a post with a SyntaxHighlighter block that contains `<?php echo 'Hello World'; ?>`
  and has the code language set to PHP.
* With each post, change the editor settings from Visual Editor to Code Editor. You'll see that they both appear to contain the same content within the block grammar: `&lt;?php echo 'Hello World'; ?>`
* Now view each post on the front end. The one published by the super admin will look correct, while the one published by the editor will have this: `<?php echo 'Hello World'; ?&gt;`

I believe this happens because on multisite, non-admins do not have the `unfiltered_html` capability, as suggested by @jrastaban [here](https://github.com/WordPress/learn/issues/158#issuecomment-736894569). So when the editor user publishes the post, what actually gets stored in the database is `&lt;?php echo 'Hello World'; ?&gt;`.

It looks like [this commit](https://github.com/Automattic/syntaxhighlighter/commit/3da0d51422b8fe0abd2af26c4acfefeebfc5d873) might actually fix the issue, but it hasn't been released yet. Will confirm as soon as I get the src files to build correctly...

**Comment by coreymckrill** [comment]
^ That commit didn't fix the issue when I tested, so I opened #182.

**Comment by yscik** [comment]
Still happening on `master` with non-admin roles.

**Comment by yscik** [comment]
Still happening on `master` with non-admin roles.

**Comment by l2m83** [comment]
@coreymckrill, in addition to str_replace try calling htmlspecialchars_decode
$code = str_replace( '&lt;', '<', $code );
$code = htmlspecialchars_decode( $code );

The modification was done on our wordpress installation and it seems to do the job.
