### ISSUE TITLE
Your site doesn’t include support for the SyntaxHighlighter Evolved block. You can try installing the block, convert it to a Custom HTML block, or remove it entirely.

### ISSUE THREAD

**Issue by j0eyv** [Automattic/syntaxhighlighter#270]
### Steps to Reproduce
1. Open a post where you have used the SyntaxHighliter plug-in.
2. Scroll to the block where it is used.

### What I Expected
That it still worked while upgrading WordPress to the latest version (at time of writing).

### What Happened Instead
See error. Can't use the plug-in anymore on new and existing posts but it still works on pages where it was before upgrading WordPress.

### PHP / WordPress / SyntaxHighlighter Evolved version
PHP: 7.2.34
WordPress: 6.4.1
SyntaxHighliter: 3.6.2

### Browser / OS version
Microsoft Edge

### Screenshot / Video
![image](https://github.com/Automattic/syntaxhighlighter/assets/41282854/6b1625fb-f1da-452b-ba4b-c0e7f1970281)

Plugin is installed for sure. I don't like trying to uninstall/install because i don't know what happens to active posts.

![Uploading image.png…]()

**Comment by fjorgemota** [comment]
Hello! Thanks for reporting this issue!

This should be fixed by #269, which was merged and released as 3.7.0 (already available on WordPress.org, too!). 

Could you please test it and verify if it now works? According to my tests, it should work just fine. =)

I'm closing this issue for now, but feel free to reopen or leave a comment if it doesn't. :)
