### ISSUE TITLE
how to use it on normal website?

### ISSUE THREAD

**Issue by zenithtekla** [Automattic/syntaxhighlighter#49]
I have a PHP web application (non-Wordpress) and would like to use it.
Can you guide me on the how-to?
Thanks

**Comment by Viper007Bond** [comment]
This plugin is a WordPress implementation of this script: http://alexgorbatchev.com/SyntaxHighlighter/

**Comment by zenithtekla** [comment]
I know but I tried that plugin before and can't attain full options and
line stripes..
See photos of what I'm mentioning:
https://drive.google.com/folderview?id=0B4ruhRenMo6kV0VqenphTE41R1k&usp=sharing
Any idea on how to do that?
Thanks & Regards

**Comment by Viper007Bond** [comment]
Sorry but I'm not the author of that script and I don't provide support for it, especially here.

**Comment by zenithtekla** [comment]
I'm just asking on how to implement your code/plugin on normal website..is it way so advanced that it can't integrate on a simple PHP website? 
I'm also curious for how you did add the stripe background and print icons when developing/forking the Alex's.

**Comment by Viper007Bond** [comment]
The striped background, print icons, and everything else is a part of http://alexgorbatchev.com/SyntaxHighlighter/ which I am not the author of. That's a different Alex, not me.

Your screenshots are from version 2.x of the library, while the latest and much better version is 3.x. That's why it looks different.

I did not fork it. It's a normal copy of the script. I took that library of JavaScript files and made it easy to use within WordPress. My code cannot be used outside of WordPress, but the JavaScript library I used easily can.

I'm not how I can make this any more clear.
