### ISSUE TITLE
!important Tags in CSS and Themes

### ISSUE THREAD

**Issue by ghost** [Automattic/syntaxhighlighter#73]
I think it is a little difficult to customize how the plugin looks. You added the possibility for custom css classes but they are so high level that they get overwritten by the !important tag even when using !important too. I would like a theme with a special background color but theres also the possibility missing to create a new theme. I would love to see either custom theme support or any other fix to change text color and background color easily and without losing the changes due to updating.

Edit: Just found this: https://alex.blog/wordpress-plugins/syntaxhighlighter/adding-a-new-theme/ but still its well hidden and a little complicated to do for beginners

**Comment by Viper007Bond** [comment]
The `!important`s come from upstream, from the highlighting library. They're there because otherwise themes would completely mess up the styling of the code. It is annoying, but it can't really be avoided.

I recommend copying one of the default themes into a new file, customizing it, and then registering it as a new theme,
